services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/lenslocked.com/images:/app/images
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/data/lenslocked.com/caddy:/data
    depends_on:
      - server

  db:
    user: "999:999"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/lenslocked.com/psql:/var/lib/postgresql/data/pgdata
