x-logging: &highlight-logging
  driver: fluentd
  options:
    fluentd-address: "tls://otel.highlight.io:24284"
    fluentd-async: "true"
    fluentd-sub-second-precision: "true"
    tag: "highlight.project_id=ldwy425g"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/lenslocked.com/images:/app/images
    depends_on:
      - db
    logging: *highlight-logging


  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/data/lenslocked.com/caddy:/data
    depends_on:
      - server
    logging: *highlight-logging

  db:
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging: *highlight-logging

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/data/lenslocked.com/psql
