services:
  db:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 3333:8080
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: dracula
