services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: baloo
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 3333:8080
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: dracula
